### ISSUE TITLE
;

### ISSUE THREAD

**Issue by RTX3090-TI** [DxxxxY/TokenAuth#6]
My Grandfather smoked his whole life. I was about 10 years old when my mother said to him, 'If you ever want to see your grandchildren graduate, you have to stop immediately.'. Tears welled up in his eyes when he realized what exactly was at stake. He gave it up immediately. Three years later he died of lung cancer. It was really sad and destroyed me. My mother said to me- 'Don't ever smoke. Please don't put your family through what your Grandfather put us through." I agreed. At 28, I have never touched a cigarette. I must say, I feel a very slight sense of regret for never having done it, because this has given me cancer anyway.

**Comment by DxxxxY** [comment]
what?

**Comment by notpayload1337** [comment]
LMFAOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
